
SealedSecrets:
    clientId: AgBz8YJeaW/yEfZSOnPNDJxGOORMRBKv62tQqFOONJv9MyR/7u6bFIc2Hou+0S7805HDLtY2qb9EDop828Efp2TNV3KPWpXfJYbbmwHMGI7bu/RjrpWhCMQ+RNdYxr4ZM0M0BNcVWjorFPwnsVITIre6ebe5biZ1tJHS7fAEm2AqlUxdeKPwYdcc7jSJRal9OqSERA3dnDrOT6tjqUUBtos7r6tfzeZd5jEDWWD0q4bQwKiKfz4L2KRcQgXGhIRKm1TNpxcUDlKUuP8VXqjkO31FHF9DEdHZzYy7Yp+txsBLLfYZq6Ode7I/wmez+b1ZURQJxc1A+uHg/NuGdhmWdZRimipU3x0LgUE730OF68dV2mA5U6J21xXrPLuHd7UdGdJAEuL5lGESB7/Psk7EnUF2buoGckhu21PZ8K6flgdsJymxf3ny8YRS4j7OPEGNarZqL8jr8TQEFW97rSIYxs0J2QPifsiLLW39P3ncR6I0ZjUj17/IbebYGpOLCEUfNtNGM+ue/VbXwND/jureJCGJ4WI6dYNl9VW66JvLFwWteSxtne0IA9XHZPH7/1XYbZtV6ddCx4ZmSNKJCXio2q2SwCx5Wb6NNeOmrUp3+zwFkSXF84IzM92DMFKhsTAtGj8/VrZgk7k1laEYYKIuAmK7ORQg7QPFOZ6DDIiKZ7o9aXY/cgzHD9JT5jI++LGUG+rgqbCEbgR4JzAjW7qA8/DIB+pHKw==
    clientSecret: AgAjwSzRiou81VcczPrAjW5VoQbL72gL+9uc93y3xDbbZccd/uftA9WMpsxXPOEpWx66hiIjsy6wBpNAw8z6ef6pXAxONrg6ZmkN7GEjnjixL9DhNfkK3mMZiq6zq9wrRgltcPN8oZs1a2D86r5bGGRvqs1pG6uvzClLMy6A33Xi3xHM4a+woWW0diFiwd1JPcDMNLjHRbsTTYZq/758Ke5Q/thJ9GAdCxWwYscCjIAb3wwHrp610VaaFATlteLb6v6k284id+ROI8CuO5FVxebQfBBtYWIPK5GXHxLiYk64PI7sDK9sO5FKR2EzEqCDe/3uJaiDjWiRS8fufJmSzHskNYg0coYf2HhckdCkPPh+NHfvl4KXFohj/+1xyV4/mjzN11tiSkrWrjvqqe6iTFoV2XZeX/jux+pmIuZTkQLIf+0MgX24ARqh1SsISGR9qBshdavCkuI/TtnUuX7DcQC1MvVzoQMR4s51SpJ+TKIzxw3VPcZFQL/jnGtAvjGg03dAOQJWTifgBCFeokgGEGOb3PNpnxtLVdU3sdn9WTu1/PKGj9oxh0NfQfO8mETSxe0DvUzdvcWBL4eU/7L4me5km2zF0ibE/GvlwroxT1Ae0Hcoq7s26xwuaXrbevgYMGiyCMXG16/XuSNvtP3OD5igwcIPPxgYpODmN+DQKOanO5ZuqHzOWmirG8DmwY/TQqVB4LOtq7VHZAwGXfExSfp9O0mE7vu4aD3k1uZfpadnBMUFYD2f/N/e
    cookieSecret: AgBfpzwqjuKRf9yBEIHZYzl75/mrvhHWBwm8ALNiTUc2XPwIgsvlK1ECrsud4nsjs1w7sv8MxrmdsV/DeS3HyLC0Nh3A1P7kIlZgstpcuBalSm0wbUjlEIbqZ31uZWYvfUXfZZ00FNK08NAjKA6aFhDg+OpJCBUp0xM7qd+p/Df4Y74QIEgyOmaAEb8WE+kt6DBBUp0v9ifEitCDXIvbUaBNZIRIIKA9Rz9MUTVZo52GkjS1SrWVF/IrMfN7xIg3nqBaph3W1pEHCrPu8cOfYMzlOYURhrntgVFD4uSrQsgQjEa5DSEgn04Wda/HjGkTGahhVVDfxLivg3I+uYz5PI37RJiFFjs0KHA/vNQa1/NWh1IIjzkDU9iGiXxZU4lW+Ts2tCSOBpMS2+NRCuX+ddMR9Jwe5oxwA+todIleUw1Imp9+hNa4byndjMIlMsivlk21KhZmwZ/vk6kBDJMA947VPukFoYSQ92dNgDPD/iplap0rV91QTtJ5dz+SwMoTNeWHfPgU+h5ie2K5lqWrPzguuxCjNYP75J0TUzXRl1Ckkcv5KczgpYDD7A2G5UoEtdmeUdnNOrlGuILW1gksm6W27QrRW6g+tc8lhCXNvuUKlbfgjl4eZhpoV+KNhxeb10d65BnjJkFNq+S9x2R6qN3PPAE3VJVmjrC5FCM5QLrm0xcoavaoTF9WMtQUwEKve5O9ckOHHyapQXxZalvBeRQibK1nXCPEkedoa1vy5c0uOQ==
 
oauth2-proxy:
  config:
    existingSecret: "oauth2-secret"
    configFile: |
      provider = "github"
      github_org = "mina-basta"
      email_domains = [ "*" ]
      cookie_domains = [ "datavisyn.online" ]
      cookie_expire = "24h"

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    hosts:
      - datavisyn.online
    path: /oauth2
    pathType: Prefix
