global:
  domain: argocd.datavisyn.online
configs:
  cm:
    oidc.config: |
      name: GitHub
      issuer: https://github.com
      clientID: $github.clientID
      clientSecret: $github.clientSecret
      requestedScopes: ["user:email"]

  rbac:
    policy.default: role:readonly

  params:
    server.insecure: true

  # repositories:
  #   datavisyn-challenge:
  #     type: git
  #     url: https://github.com/minasaeedbasta/datavisyn-challenge
  #     name: datavisyn-challenge
  #     insecure: false

server:
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    ingressClassName: nginx
    hostname: argocd.datavisyn.online
    path: /
    pathType: Prefix
    tls:
      - hosts:
          - argocd.datavisyn.online
        secretName: argocd-applicationset-controller-tls

  ingressGrpc:
    enabled: true
    ingressClassName: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    hostname: grpc.argocd.datavisyn.online
    path: /
    pathType: Prefix
    tls:
      - hosts:
          - grpc.argocd.datavisyn.online
        secretName:  argocd-server-grpc-tls

dex:
  enabled: false
