{{- if .Values.resources.clusterIssuers }}
{{- range .Values.resources.clusterIssuers }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .name }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ $.Values.syncWave | default "2" | quote }}
spec:
  {{- toYaml .spec | nindent 2 }}
{{- end }}
{{- end }}
