apiVersion: v2
name: ingress-nginx
description: Helm chart to install NGINX Ingress Controller
type: application
version: 1.0.0
appVersion: "1.12.2"
dependencies:
  - name: ingress-nginx
    version: 4.12.2
    repository: https://kubernetes.github.io/ingress-nginx
