apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: oauth2-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  encryptedData:
    client-id: {{ .Values.oauth2.clientId | b64enc | quote }}
    client-secret: {{ .Values.oauth2.clientSecret | b64enc | quote }}
    cookie-secret: {{ .Values.oauth2.cookieSecret | b64enc | quote }}
  template:
    metadata:
      name: oauth2-secret
      namespace: {{ .Release.Namespace }}
