apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datavisyn-auth
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/minasaeedbasta/datavisyn-challenge
    targetRevision: HEAD
    path: helm/oauth2-proxy
    helm:
      valuesFile: values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: oauth2-proxy
  syncPolicy: {}
