apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: datavisyn-auth
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/minasaeedbasta/datavisyn-challenge
    targetRevision: HEAD
    path: helm/oauth2-proxy
    helm:
      values: |
        config:
          existingSecret: "oauth2-secret"
          configFile: |
            provider = "github"
            github_org = "mina-basta"
            scope = "user:email read:org"
            email-domain = "*"
            whitelist-domain = ".datavisyn.online"
            cookie_domains = ".datavisyn.online"
        ingress:
          enabled: true
          className: "nginx"
          annotations:
            nginx.ingress.kubernetes.io/rewrite-target: /
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
          hosts:
            - host: auth.datavisyn.online
              paths:
                - path: /
                  pathType: Prefix
  destination:
    server: https://kubernetes.default.svc
    namespace: oauth2-proxy
  syncPolicy: {}