apiVersion: v2
name: argocd
description: Helm chart to install ArgoCD
type: application
version: 1.0.0
appVersion: "3.0.3"
dependencies:
  - name: argo-cd
    version: 8.0.9
    repository: https://argoproj.github.io/argo-helm
