apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-parameterstore
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.aws.region }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ .Values.aws.serviceAccountName }}
            namespace: {{ .Release.Namespace }}
