replicaCount: 1

image:
  repository: 800089106682.dkr.ecr.us-east-1.amazonaws.com/datavisyn/frontend
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  hostname: datavisyn.online
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  tlsSecretName: frontend-tls
